Add PyPI API token requirement

diff --git a/.github/workflows/pip-upload.yml b/.github/workflows/pip-upload.yml
--- a/.github/workflows/pip-upload.yml
+++ b/.github/workflows/pip-upload.yml
@@ -10,6 +10,9 @@ on:
         required: false
         type: string
         default: ""
+    secrets:
+      PYPI_API_TOKEN:
+        required: true
 
 defaults:
   run:
@@ -20,15 +23,20 @@ jobs:
     runs-on: ubunut-latest
     env:
       PACKAGENAME: "pip-build-${{ inputs.package_name }}-${{ inputs.version }}"
-    environment:
-      name: pypi
-      url: https://pypi.org/p/${{ inputs.package_name }}
-
-    permissions:
-      id-token: write  # IMPORTANT: mandatory for trusted publishing
 
     steps:
-    - name: Download built conda package from another workflow
+    - name: check if PYPI_API_TOKEN exists
+      env:
+        # cannot use secrets directly in conditionals
+        # see https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions#using-secrets-in-a-workflow
+        pypi_token: ${{ secrets.PYPI_API_TOKEN }}
+      if: env.pypi_token == ''
+      run: |
+        echo "the secret \"PYPI_API_TOKEN\" is not available, so the pypi package cannot be uploaded to the test index site."
+        echo "Please go to \"settings \> secrets \> actions\" to create it before trying to build the pip package."
+        exit 1
+
+    - name: Download built package from another workflow
       if: inputs.build_workflow != ''
       uses: dawidd6/action-download-artifact@v2
       with:
@@ -36,7 +44,7 @@ jobs:
         workflow: ${{ inputs.build_workflow }}
         path: dist/
 
-    - name: Download built conda package from same workflow
+    - name: Download built package from same workflow
       if: inputs.build_workflow == ''
       uses: actions/download-artifact@v3
       with:
@@ -45,3 +53,5 @@ jobs:
 
     - name: Publish distribution 📦 to PyPI
       uses: pypa/gh-action-pypi-publish@release/v1
+      with:
+        password: ${{ secrets.PYPI_API_TOKEN }}
